AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  onesearch-mediaconvert-sam

  Sample SAM Template for onesearch-mediaconvert-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ricepotato-media-convert-ap-northeast-2
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: True    

  MediaCreatedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.media_created_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          MEDIA_OUTPUT_BUCKET: cf-simple-s3-origin-ricepotato-cdn-632854243364
          MEDIA_CONVERT_REGION: ap-northeast-2
      Events:
        S3MediaCreated:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: media/

  MediaConvertStateChangedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.media_convert_job_state_change_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        MediaConvertStateChangeEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.mediaconvert
              detail-type:
                  - MediaConvert Job State Change
              detail:
                status:
                  - COMPLETE
                  - ERROR
                  - CANCELED

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MediaCreatedFunction:
    Description: "Media Created Function ARN"
    Value: !GetAtt MediaCreatedFunction.Arn

  MediaCreatedFunctionIamRole:
    Description: "Implicit IAM Role created for MediaCreatedFunction function"
    Value: !GetAtt MediaCreatedFunctionRole.Arn

  MediaConvertStateChangedFunction:
    Description: "Media Convert State Change Function ARN"
    Value: !GetAtt MediaConvertStateChangedFunction.Arn

  MediaConvertStateChangedFunctionIamRole:
    Description: "Implicit IAM Role created for MediaConvertStateChangedFunction function"
    Value: !GetAtt MediaConvertStateChangedFunctionRole.Arn

