AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  onesearch-mediaconvert-sam

  Sample SAM Template for onesearch-mediaconvert-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  MediaBucket:
    Type: String
    Description: S3 bucket for media files
  
  AWSRegion:
    Type: String
    Description: AWS Region

Resources:
  MediaCreatedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: app.media_created_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          MEDIA_BUCKET: !Ref MediaBucket
          AWS_REGION: !Ref AWS::Region
      Events:
        S3MediaCreated:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket: !Ref MediaBucket # cf-simple-s3-origin-ricepotato-cdn-632854243364
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: media/

  MediaConvertStateChangedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.media_convert_job_state_change_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  MediaConvertJobStateChangeEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: "MediaConvert Job State Change Event"
      EventPattern:
        source:
          - aws.mediaconvert
        detail-type:
          - MediaConvert Job State Change
        detail:
          status:
            - COMPLETE
            - ERROR
            - CANCELED
      Targets:
        - Arn: !GetAtt MediaConvertStateChangedFunction.Arn
          Id: MediaConvertStateChangedFunction

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MediaCreatedFunction:
    Description: "Media Created Function ARN"
    Value: !GetAtt MediaCreatedFunction.Arn

  MediaConvertStateChangedFunction:
    Description: "MediaConvert Job State Change Function ARN"
    Value: !GetAtt MediaConvertStateChangedFunction.Arn

  MediaConvertJobStateChangeEvent:
    Description: "MediaConvert Job State Change Event ARN"
    Value: !Ref MediaConvertJobStateChangeEvent

  MediaConvertJobStateChangeEvent:
    Description: "MediaConvert Job State Change Event ARN"
    Value: !Ref MediaConvertJobStateChangeEvent

  MediaCreatedFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MediaCreatedFunctionRole.Arn
